spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hello?characterEncoding=UTF-8
    username: root
    password: superzhang
    driver-class-name: com.mysql.jdbc.Driver

  devtools:
    restart:
      enabled: true










